Feature: Checking Django failure

  Scenario Outline: A plain scenario
    Given I run a step

    Examples:
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
      | unused |
